git rm -r LAVFilters/libbluray/libbluray.vcxproj.filters
git rm -r LAVFilters/qsdecoder/IntelQuickSyncDecoder.vcxproj.filters
git rm -r Src/Server/Server.vcxproj.filters
git rm -r Src/media/media.filters
git rm -r StormWebrtc/External/asio/asio.vcxproj.filters
git rm -r StormWebrtc/External/mbedtls/mbedtls.vcxproj.filters
git rm -r StormWebrtc/External/usrsctplib/usrsctplib.vcxproj.filters
git rm -r StormWebrtc/StormWebrtc/StormWebrtc.vcxproj.filters
git rm -r StormWebrtc/StormWebrtcClientAPI/StormWebrtcClientAPI.vcxproj.filters
git rm -r StormWebrtc/StormWebrtcClientTest/StormWebrtcClientTest.vcxproj.filters
git rm -r StormWebrtc/StormWebrtcServerAPI/StormWebrtcServerAPI.vcxproj.filters
git rm -r StormWebrtc/StormWebrtcTest/StormWebrtcTest.vcxproj.filters
git rm -r ThirdParty/apache-log4cxx-0.10.0/projects/log4cxx.vcxproj.filters
git rm -r ThirdParty/apr-util/aprutil.vcxproj.filters
git rm -r ThirdParty/apr/apr.vcxproj.filters
git rm -r ThirdParty/glib-2.28.8/build/win32/vs10/gio.vcxproj.filters
git rm -r ThirdParty/glib-2.28.8/build/win32/vs10/glib-compile-schemas.vcxproj.filters
git rm -r ThirdParty/glib-2.28.8/build/win32/vs10/glib-genmarshal.vcxproj.filters
git rm -r ThirdParty/glib-2.28.8/build/win32/vs10/glib.vcxproj.filters
git rm -r ThirdParty/glib-2.28.8/build/win32/vs10/gmodule.vcxproj.filters
git rm -r ThirdParty/glib-2.28.8/build/win32/vs10/gobject.vcxproj.filters
git rm -r ThirdParty/glib-2.28.8/build/win32/vs10/gsettings.vcxproj.filters
git rm -r ThirdParty/glib-2.28.8/build/win32/vs10/gspawn-win32-helper-console.vcxproj.filters
git rm -r ThirdParty/glib-2.28.8/build/win32/vs10/gspawn-win32-helper.vcxproj.filters
git rm -r ThirdParty/glib-2.28.8/build/win32/vs10/gthread.vcxproj.filters
git rm -r ThirdParty/glib-2.28.8/build/win32/vs10/testglib.vcxproj.filters
git rm -r ThirdParty/httpclient/httpclient.vcxproj.filters
git rm -r ThirdParty/jsoncpp-1.6.5/src/jsoncpp.vcxproj.filters
git rm -r ThirdParty/libevent/event.vcxproj.filters
git rm -r ThirdParty/libevent/event_core.vcxproj.filters
git rm -r ThirdParty/libevent/event_extra.vcxproj.filters
git rm -r ThirdParty/libnice-0.1.4/win32/vs9/libnice.vcxproj.filters
git rm -r ThirdParty/libnice-0.1.4/win32/vs9/test-add-remove-stream.vcxproj.filters
git rm -r ThirdParty/libnice-0.1.4/win32/vs9/test-address.vcxproj.filters
git rm -r ThirdParty/libnice-0.1.4/win32/vs9/test-bind.vcxproj.filters
git rm -r ThirdParty/libnice-0.1.4/win32/vs9/test-dribble.vcxproj.filters
git rm -r ThirdParty/libnice-0.1.4/win32/vs9/test-fallback.vcxproj.filters
git rm -r ThirdParty/libnice-0.1.4/win32/vs9/test-fullmode.vcxproj.filters
git rm -r ThirdParty/libnice-0.1.4/win32/vs9/test-parse.vcxproj.filters
git rm -r ThirdParty/libnice-0.1.4/win32/vs9/test-pseudotcp.vcxproj.filters
git rm -r ThirdParty/libnice-0.1.4/win32/vs9/test-restart.vcxproj.filters
git rm -r ThirdParty/libnice-0.1.4/win32/vs9/test-thread.vcxproj.filters
git rm -r ThirdParty/libnice-0.1.4/win32/vs9/test.vcxproj.filters
git rm -r ThirdParty/srtp/srtp.vcxproj.filters
git rm -r ThirdParty/zlib/zlib.vcxproj.filters
git rm -r WinCustomDesktop/CDConfig/CDConfig.vcxproj.filters
git rm -r WinCustomDesktop/CustomDesktop/CustomDesktop.vcxproj.filters
git rm -r WinCustomDesktop/Inject/Inject.vcxproj.filters
git rm -r WinCustomDesktop/Plugin/DesktopBrowser/DesktopBrowser.vcxproj.filters
git rm -r WinCustomDesktop/Plugin/MaskDesktop/MaskDesktop.vcxproj.filters
git rm -r WinCustomDesktop/Plugin/VideoDesktop/VideoDesktop.vcxproj.filters
git rm -r WinCustomDesktop/Plugin/WIMC/WIMC.vcxproj.filters
git rm -r licodecore/third_party/webrtc/src/webrtc/system_wrappers/system_wrappers.vcxproj.filters
git rm -r pjproject-2.9/pjlib-util/build/pjlib_util.vcxproj.filters
git rm -r pjproject-2.9/pjlib-util/build/pjlib_util_test.vcxproj.filters
git rm -r pjproject-2.9/pjlib/build/pjlib.vcxproj.filters
git rm -r pjproject-2.9/pjlib/build/pjlib_test.vcxproj.filters
git rm -r pjproject-2.9/pjmedia/build/pjmedia.vcxproj.filters
git rm -r pjproject-2.9/pjmedia/build/pjmedia_audiodev.vcxproj.filters
git rm -r pjproject-2.9/pjmedia/build/pjmedia_codec.vcxproj.filters
git rm -r pjproject-2.9/pjmedia/build/pjmedia_test.vcxproj.filters
git rm -r pjproject-2.9/pjmedia/build/pjmedia_videodev.vcxproj.filters
git rm -r pjproject-2.9/pjnath/build/pjnath.vcxproj.filters
git rm -r pjproject-2.9/pjnath/build/pjnath_test.vcxproj.filters
git rm -r pjproject-2.9/pjsip-apps/build/pjsua.vcxproj.filters
git rm -r pjproject-2.9/pjsip-apps/build/pjsystest.vcxproj.filters
git rm -r pjproject-2.9/pjsip-apps/build/python_pjsua.vcxproj.filters
git rm -r pjproject-2.9/pjsip-apps/build/sample_debug.vcxproj.filters
git rm -r pjproject-2.9/pjsip-apps/build/samples.vcxproj.filters
git rm -r pjproject-2.9/pjsip-apps/build/swig_java_pjsua2.vcxproj.filters
git rm -r pjproject-2.9/pjsip-apps/src/pjsua/winrt/cli/comp/pjsua_cli_shared_comp.vcxitems.filters
git rm -r pjproject-2.9/pjsip-apps/src/pjsua/winrt/cli/comp/pjsua_cli_uwp_comp.vcxproj.filters
git rm -r pjproject-2.9/pjsip-apps/src/pjsua/winrt/cli/comp/pjsua_cli_wp8_comp.vcxproj.filters
git rm -r pjproject-2.9/pjsip-apps/src/pjsua/winrt/gui/uwp/VoipBackEnd/VoipBackEnd.vcxproj.filters
git rm -r pjproject-2.9/pjsip-apps/src/pjsua/winrt/gui/uwp/VoipHost/VoipHost.vcxproj.filters
git rm -r pjproject-2.9/pjsip/build/pjsip_core.vcxproj.filters
git rm -r pjproject-2.9/pjsip/build/pjsip_simple.vcxproj.filters
git rm -r pjproject-2.9/pjsip/build/pjsip_test.vcxproj.filters
git rm -r pjproject-2.9/pjsip/build/pjsip_ua.vcxproj.filters
git rm -r pjproject-2.9/pjsip/build/pjsua2_lib.vcxproj.filters
git rm -r pjproject-2.9/pjsip/build/pjsua_lib.vcxproj.filters
git rm -r pjproject-2.9/third_party/build/baseclasses/libbaseclasses.vcxproj.filters
git rm -r pjproject-2.9/third_party/build/g7221/libg7221codec.vcxproj.filters
git rm -r pjproject-2.9/third_party/build/gsm/libgsmcodec.vcxproj.filters
git rm -r pjproject-2.9/third_party/build/ilbc/libilbccodec.vcxproj.filters
git rm -r pjproject-2.9/third_party/build/milenage/libmilenage.vcxproj.filters
git rm -r pjproject-2.9/third_party/build/resample/libresample.vcxproj.filters
git rm -r pjproject-2.9/third_party/build/speex/libspeex.vcxproj.filters
git rm -r pjproject-2.9/third_party/build/srtp/libsrtp.vcxproj.filters
git rm -r pjproject-2.9/third_party/build/webrtc/libwebrtc.vcxproj.filters
git rm -r pjproject-2.9/third_party/build/yuv/libyuv.vcxproj.filters
git rm -r vosvideoserver/VosVideo.Camera/VosVideo.Camera.vcxproj.filters
git rm -r vosvideoserver/VosVideo.CameraPlayer/VosVideo.CameraPlayer.vcxproj.filters
git rm -r vosvideoserver/VosVideo.Common/VosVideo.Common.vcxproj.filters
git rm -r vosvideoserver/VosVideo.Communication.Casablanca/VosVideo.Communication.Casablanca.vcxproj.filters
git rm -r vosvideoserver/VosVideo.Communication.InterprocessQueue/VosVideo.Communication.InterprocessQueue.vcxproj.filters
git rm -r vosvideoserver/VosVideo.Communication/VosVideo.Communication.vcxproj.filters
git rm -r vosvideoserver/VosVideo.Configuration/VosVideo.Configuration.vcxproj.filters
git rm -r vosvideoserver/VosVideo.Data/VosVideo.Data.vcxproj.filters
git rm -r vosvideoserver/VosVideo.DeviceManagement/VosVideo.DeviceManagement.vcxproj.filters
git rm -r vosvideoserver/VosVideo.GSCameraPlayer/VosVideo.GSCameraPlayer.vcxproj.filters
git rm -r vosvideoserver/VosVideo.MFCameraPlayer/VosVideo.MFCameraPlayer.vcxproj.filters
git rm -r vosvideoserver/VosVideo.MediaFile/VosVideo.MediaFile.vcxproj.filters
git rm -r vosvideoserver/VosVideo.MediaManagement/VosVideo.MediaManagement.vcxproj.filters
git rm -r vosvideoserver/VosVideo.UserManagement/VosVideo.UserManagement.vcxproj.filters
git rm -r vosvideoserver/VosVideo.WebRtc/VosVideo.WebRtc.vcxproj.filters
git rm -r vosvideoserver/deviceworker/deviceworker.vcxproj.filters
git rm -r vosvideoserver/rtbcserver/rtbcserver.vcxproj.filters
git rm -r vosvideoserver/test/VosVideo.Camera.Test/VosVideo.Camera.Test.vcxproj.filters
	git rm -r vosvideoserver/test/VosVideo.Communication.Test/VosVideo.Communication.Test.vcxproj.filters
	git rm -r vosvideoserver/test/VosVideo.Data.Test/VosVideo.Data.Test.vcxproj.filters
	git rm -r vosvideoserver/test/VosVideo.DeviceManagement.Test/VosVideo.DeviceManagement.Test.vcxproj.filters
	git rm -r vosvideoserver/test/VosVideo.Test.Common/VosVideo.Test.Common.vcxproj.filters
	git rm -r vosvideoserver/test/VosVideo.UserManagement.Test/VosVideo.UserManagement.Test.vcxproj.filters
	git rm -r vosvideoserver/test/VosVideo.WebRtc.Test/VosVideo.WebRtc.Test.vcxproj.filters
	git rm -r vosvideoserver/test/VosVideo.WebmSegmenter.Test/VosVideo.WebmSegmenter.Test.vcxproj.filters

